;;; financial-chart-eas-catalog-examples-test.el --- an example and golden per catalog entry -*- lexical-binding: t; -*-

;;; Commentary:

;; fc-gbo.3: every study and kind of annotation has an example chart
;; (examples/indicators/NAME.json, regenerated by
;; src/examples/render-indicator-catalog.el) that compiles to a spec
;; eas draws natively, with a text golden under test/golden/indicators/
;; (and SVG goldens for a representative few).  EAS_UPDATE_GOLDEN=1 (or
;; FINANCIAL_CHART_UPDATE_GOLDEN=1) rewrites them.

;;; Code:

(require 'ert)
(require 'financial-chart-test-support)
(require 'financial-chart)

(defconst financial-chart-catalog-examples-test--svg
  '("ichimoku" "bollinger" "pivots" "rsi" "macd" "markers" "annotations" "fibonacci")
  "Examples with an SVG golden too.")

(defun financial-chart-catalog-examples-test--golden (name actual)
  "Compare ACTUAL with golden NAME under test/golden/indicators/."
  (let ((file (expand-file-name name (expand-file-name "test/golden/indicators" financial-chart-test-root)))
        (update (or (getenv "EAS_UPDATE_GOLDEN") (getenv "FINANCIAL_CHART_UPDATE_GOLDEN"))))
    (if (or update (not (file-exists-p file)))
        (progn
          (make-directory (file-name-directory file) t)
          (with-temp-file file
            (set-buffer-file-coding-system 'utf-8-unix)
            (insert actual))
          (unless update
            (ert-fail (format "Golden %s was missing and has been written; review and rerun" name))))
      (should (equal (with-temp-buffer (insert-file-contents file) (buffer-string)) actual)))))

(ert-deftest financial-chart-catalog-examples-cover-every-study-and-annotation ()
  (let* ((names (financial-chart-catalog-examples))
         (types (delete-dups
                 (cl-loop for name in names
                          for chart = (financial-chart-catalog-example name)
                          append (cl-loop for pane in (cons (plist-get chart :price)
                                                            (append (plist-get chart :panes) nil))
                                          append (mapcar (lambda (a) (plist-get a :type))
                                                         (plist-get pane :annotations)))))))
    (dolist (study (mapcar #'car financial-chart-studies))
      (should (member study names)))
    (dolist (type financial-chart-annotation-types)
      (should (member type types)))
    (should (= (length names) (+ (length financial-chart-studies) 3)))))

(ert-deftest financial-chart-catalog-examples-draw-natively-with-text-goldens ()
  (dolist (name (financial-chart-catalog-examples))
    (let ((chart (financial-chart-catalog-example name)))
      (should (equal (list name (eas-spec-unsupported (financial-chart-compose chart))) (list name nil)))
      (financial-chart-catalog-examples-test--golden
       (format "%s.txt" name)
       (substring-no-properties (financial-chart-compose-render chart :width 100 :height 34))))))

(ert-deftest financial-chart-catalog-examples-svg ()
  (dolist (name (financial-chart-catalog-examples))
    (let ((svg (financial-chart-compose-render (financial-chart-catalog-example name)
                                               :backend 'svg :width 720 :height 460)))
      (should (string-prefix-p "<svg" svg))
      (when (member name financial-chart-catalog-examples-test--svg)
        (financial-chart-catalog-examples-test--golden
         (format "%s.svg" name) (concat (replace-regexp-in-string "><" ">\n<" svg) "\n"))))))

(ert-deftest financial-chart-catalog-example-errors ()
  (let ((err (should-error (financial-chart-catalog-example "renko") :type 'financial-chart-invalid-chart)))
    (should (equal (plist-get (cddr err) :code) "NOT_FOUND"))
    (should (string-match-p "ichimoku" (cadr err)))))

(provide 'financial-chart-eas-catalog-examples-test)
;;; financial-chart-eas-catalog-examples-test.el ends here
