;;; financial-chart-trend-strength-test.el --- Trend indicator tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'seq)
(defvar financial-chart-trend-strength-test--dir
  (file-name-directory (or load-file-name buffer-file-name)))
(add-to-list 'load-path (expand-file-name ".." financial-chart-trend-strength-test--dir))
(require 'financial-chart-trend-strength)

(defconst financial-chart-trend-strength-test--bars
  '((:high 10 :low 8 :close 9)
    (:high 12 :low 9 :close 11)
    (:high 13 :low 10 :close 12)
    (:high 14 :low 11 :close 13)
    (:high 15 :low 12 :close 14)
    (:high 16 :low 13 :close 15)))

(ert-deftest financial-chart-trend-dmi-returns-aligned-named-series ()
  (let* ((outputs (financial-chart-dmi financial-chart-trend-strength-test--bars 2))
         (plus (plist-get (nth 0 outputs) :values))
         (minus (plist-get (nth 1 outputs) :values))
         (adx (plist-get (nth 2 outputs) :values)))
    (should (equal (mapcar (lambda (output) (plist-get output :name)) outputs)
                   '(plus-di minus-di adx)))
    (should (= (length plus) (length financial-chart-trend-strength-test--bars)))
    (should (equal (seq-take plus 2) '(nil nil)))
    (should (> (nth 2 plus) 0))
    (should (equal (seq-take minus 3) '(nil nil 0.0)))
    (should (equal (seq-take adx 3) '(nil nil nil)))
    (should (= (nth 3 adx) 100.0))))

(ert-deftest financial-chart-trend-dmi-resets-after-missing-bars ()
  (let* ((bars (append (seq-take financial-chart-trend-strength-test--bars 3)
                       (list '(:high 20 :close 19))
                       (seq-drop financial-chart-trend-strength-test--bars 3)))
         (outputs (financial-chart-dmi bars 2)))
    (should (null (nth 3 (plist-get (nth 0 outputs) :values))))
    (should (null (nth 4 (plist-get (nth 0 outputs) :values))))))

(ert-deftest financial-chart-trend-aroon-uses-period-plus-one-window ()
  (let* ((outputs (financial-chart-aroon financial-chart-trend-strength-test--bars 2))
         (up (plist-get (nth 0 outputs) :values))
         (down (plist-get (nth 1 outputs) :values)))
    (should (equal up '(nil nil 100.0 100.0 100.0 100.0)))
    (should (equal down '(nil nil 0.0 0.0 0.0 0.0)))
    (should (= (length up) (length financial-chart-trend-strength-test--bars))))
  (let* ((bars '((:high 10 :low 8) (:high 11 :low 9) (:high 11 :low 10)))
         (values (plist-get (car (financial-chart-aroon bars 2)) :values)))
    (should (= (nth 2 values) 100.0))))

(ert-deftest financial-chart-trend-aroon-preserves-missing-windows-as-nil ()
  (let* ((bars '((:high 10 :low 8) (:high 11 :low 9) (:high 12)
                 (:high 13 :low 10) (:high 14 :low 11)
                 (:high 15 :low 12)))
         (outputs (financial-chart-aroon bars 2)))
    (should (equal (plist-get (car outputs) :values)
                   '(nil nil nil nil nil 100.0)))
    (should (equal (length (plist-get (cadr outputs) :values)) (length bars)))))

(ert-deftest financial-chart-trend-parabolic-sar-aligns-and-reverses ()
  (let* ((bars '((:high 10 :low 8 :close 9)
                 (:high 12 :low 9 :close 11)
                 (:high 13 :low 10 :close 12)
                 (:high 14 :low 11 :close 13)
                 (:high 13 :low 8 :close 9)))
         (values (financial-chart-parabolic-sar bars)))
    (should (= (length values) (length bars)))
    (should (null (car values)))
    (should (= (nth 1 values) 8))
    (should (= (nth 2 values) 8)))
  (let ((values (financial-chart-parabolic-sar
                 '((:high 10 :low 8 :close 9)
                   (:high 12 :low 9 :close 11)
                   (:high 13 :low 10 :close 12)
                   (:high 14 :low 11 :close 13)
                   (:high 13 :low 8 :close 9)))))
    (should (= (nth 4 values) 14))))

(ert-deftest financial-chart-trend-strength-register-with-api ()
  (let ((names (mapcar (lambda (entry) (plist-get entry :name))
                       (financial-chart-list-indicators))))
    (should (memq 'dmi names))
    (should (memq 'aroon names))
    (should (memq 'parabolic-sar names)))
  (let ((bars financial-chart-trend-strength-test--bars))
    (should (= (length (financial-chart-indicator-evaluate 'dmi bars 2)) 3))))

(provide 'financial-chart-trend-strength-test)
;;; financial-chart-trend-strength-test.el ends here

